language: node_js

sudo: required

node_js: '10'

branches:
  only:
    - hexo

before_install:
  - export TZ='Asia/Shanghai'
  # - export HEXO_ALGOLIA_INDEXING_KEY=$HEXO_ALGOLIA_KEY
  # - yarn global add hexo-cli

install:
  - yarn install

script:
  # - hexo clean
  # - hexo generate
  # - hexo algolia
  - yarn run build
  #  Add CNAME record 'spencerwoo.com' after each build
  - echo "spencerwoo.com" > public/CNAME
  - ls ./public/assets
  - ls ./public/assets/img

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  name: $GIT_NAME
  email: $GIT_EMAIL
  keep-history: true
  target-branch: master
  on:
    branch: hexo
