language: node_js

node_js: stable

install:
  - npm install

cache: 
  directories: 
    - "node_modules"

branches:
  only:
    - hexo

before_install: 
  - export TZ='Asia/Shanghai'
  - npm install hexo-cli -g

install:
  - npm install
  - npm install hexo-deployer-git --save

script:
  - hexo clean
  - hexo generate

after_script:
  - git config user.name "${GIT_NAME}"
  - git config user.email "{$GIT_EMAIL}"
  - sed -i "s/gh_token/${GITHUB_TOKEN}/g" ./_config.yml